---
- name: Start the template creation process (from scratch)
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    resource_group: myRG01
    location: westeurope
    storageaccount: sssaaa01
    virtualnetwork: virtualnetwork01
    subnet: subnet01
    public_ip: public_ip01
    security_ssh: security_ssh01
    test_nic: test_nic01
    vm_name: w2016-stage10000001
    username: azureuser
    password: PassWord@0329
    tenant_id: 72f988bf-86f1-41af-91ab-2d7cd011db47
    sub_id: 2085065b-00f8-4cba-9675-ba15f4d4ab66
    secret: 531dcffa-3aff-4488-99bb-4816c395ea3f
    client_id: eec5624a-90f8-4386-8a87-02730b5410d5
  tasks:
  - name: create resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"

  - name: create storage account
    azure_rm_storageaccount:
      resource_group: "{{ resource_group }}"
      name: "{{ storageaccount }}"
      account_type: Standard_LRS

  - name: create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ resource_group }}"
      name: "{{ virtualnetwork }}"
      address_prefixes: "10.0.0.0/16"

  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ resource_group }}"
      name: "{{ subnet }}"
      address_prefix: "10.0.1.0/24"
      virtual_network: "{{ virtualnetwork }}"

  - name: create public ip
    azure_rm_publicipaddress:
      resource_group: "{{ resource_group }}"
      allocation_method: Static
      name: "{{ public_ip }}"
  
  - name: Create security group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{ resource_group }}"
      name: "{{ security_ssh }}"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 101
          direction: Inbound
  
  - name: Create NIC
    azure_rm_networkinterface:
      resource_group: "{{ resource_group }}"
      name: "{{ test_nic }}"
      virtual_network: "{{ virtualnetwork }}"
      subnet: "{{ subnet }}"
      public_ip_name: "{{ public_ip}}"
      security_group: "{{ security_ssh }}"

  - name: Create Azure VM with Ansible
    azure_rm_virtualmachine:
      admin_username: "{{ username }}"
      admin_password: "{{ password }}"
#      client_id: "{{ client_id }}"
      image:
        publisher: Canonical
        offer: UbuntuServer
        sku: 16.04-LTS
        version: latest
      location: "{{ location }}"
      name: "{{ vm_name }}"
      os_type: Linux 
      resource_group: "{{ resource_group }}"
#      secret: "{{ secret }}"
      state: present
      storage_account_name: "{{ storageaccount }}"
      virtual_network_name: "{{ virtualnetwork }}"
#      subscription_id: "{{ sub_id }}"
#      tenant: "{{ tenant_id }}"
      vm_size: Standard_A0
