---
- name: "create and update the tags on a VM"
  hosts: localhost
  vars: 
    rg: myRG01
    location: westeurope
    vmname: myVM04

  tasks: 
  - name: Create Resource Group
    azure_rm_resourcegroup:
      name: "{{ rg }}"
      location: "{{ location }}"

  - name: Create {{vmname}} VM 
    azure_rm_virtualmachine:
      resource_group: '{{ rg }}'
      name: '{{vmname}}'
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      admin_password: Password@0329
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: '16.04-LTS'
        version: latest
      append_tags: no
      tags: 
        'foo': 'bar'

  - name: Append tags to {{vmname}}
    azure_rm_virtualmachine:
      resource_group: '{{ rg }}'
      name: '{{vmname}}'
      vm_size: Standard_DS1_v2
      append_tags: yes
      tags: 
        'derp': 'snort'
