---
# This playbook create an Azure VM with public IP
# Change variables below to customize you VM deployment
- name: Create Azure VM
  hosts: localhost
#  conneciton: local
  vars:
#    resource_group: demo_vm0000
    resource_group: MyAnsibleGroup
    resource_group_secondary: demo_vm_1
    vm_name: testvm
    location: eastus
#  roles:
#    - Azure.azure_modules
  tasks:
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      admin_password: Password@123
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: 16.04-LTS
        version: latest

